(ns kintone-client.constant.path.app
  {:no-doc true})

(def app "/v1/app.json")
(def form "/v1/form.json")
(def apps "/v1/apps.json")
(def form-layout "/v1/app/form/layout.json")
(def preview-form-layout "/v1/preview/app/form/layout.json")
(def form-fields "/v1/app/form/fields.json")
(def preview-form-fields "/v1/preview/app/form/fields.json")
(def preview-app "/v1/preview/app.json")
(def preview-deploy "/v1/preview/app/deploy.json")
(def views "/v1/app/views.json")
(def preview-views "/v1/preview/app/views.json")
(def settings "/v1/app/settings.json")
(def preview-settings "/v1/preview/app/settings.json")
(def status "/v1/app/status.json")
(def preview-status "/v1/preview/app/status.json")
(def customize "/v1/app/customize.json")
(def preview-customize "/v1/preview/app/customize.json")
(def acl "/v1/app/acl.json")
(def preview-acl "/v1/preview/app/acl.json")
(def field-acl "/v1/field/acl.json")
(def preview-field-acl "/v1/preview/field/acl.json")
