name: Lint and Test

on: push

jobs:
  clj_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cljstyle: latest
      - run: make format-check

  clj_kondo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeLaGuardo/setup-clojure@master
        with:
          clj-kondo: latest
      - run: make lint

  test:
    needs: [clj_style, clj_kondo]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: jdk
          architecture: x64

      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: '2.11.2'

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: '18.16.1'
          cache: pnpm

      - name: Show versions
        run: |
          java -version
          lein version
          pnpm -v

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2
            ~/.lein
          key: clj-cache-test-${{ hashFiles('project.clj') }}
          restore-keys: |
            clj-cache-test-

      - run: pnpm i --frozen-lockfile

      - name: Run tests
        run: make test
